### ISSUE TITLE
Bug:  if the string column has more then 1024 chars, the result will be truncated

### ISSUE THREAD

**Issue by dmks** [nanodbc/nanodbc#166] opened 2018-03-25 19:28 UTC
## Environment

* nanodbc version:
master

* DBMS name/version:
* ODBC connection string:
* OS and Compiler:
* CMake settings:

## Actual behavior
if the string column has more then 1024 chars, the result will be truncated

## Expected  behavior
should return the whole data.

## Minimal Working Example

Here is the fix:
```
diff --git a/nanodbc/nanodbc.cpp b/nanodbc/nanodbc.cpp
index 3c2cadb..0e82853 100644
--- a/nanodbc/nanodbc.cpp
+++ b/nanodbc/nanodbc.cpp
@@ -2924,14 +2924,15 @@ inline void result::result_impl::get_ref_impl(short column, T& result) const
                     buffer,          // TargetValuePtr
                     buffer_size,     // BufferLength
                     &ValueLenOrInd); // StrLen_or_IndPtr
-                if (ValueLenOrInd > 0)
-                    out.append(
-                        buffer,
-                        std::min<std::size_t>(
-                            ValueLenOrInd,
-                            col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1));
+                if (ValueLenOrInd == SQL_NO_TOTAL || ValueLenOrInd > 0)
+                  out.append(
+                      buffer,
+                      ValueLenOrInd == SQL_NO_TOTAL ?
+                        (col.ctype_ == SQL_C_BINARY ? buffer_size : buffer_size - 1) :
+                        ValueLenOrInd
+                  );
                 else if (ValueLenOrInd == SQL_NULL_DATA)
-                    col.cbdata_[static_cast<size_t>(rowset_position_)] = (SQLINTEGER)SQL_NULL_DATA;
+                  col.cbdata_[static_cast<size_t>(rowset_position_)] = (SQLINTEGER)SQL_NULL_DATA;
                 // Sequence of successful calls is:
                 // SQL_NO_DATA or SQL_SUCCESS_WITH_INFO followed by SQL_SUCCESS.
             } while (rc == SQL_SUCCESS_WITH_INFO);```

**Comment by mloskot** [comment] 2018-03-25 20:12
Looks like duplicate of #160

Fix proposed in #161

**Closed by mloskot** 2018-03-25 20:12 UTC
