### ISSUE TITLE
[MSSQL] SQL_TIME or SQL_TYPE_TIME not supported but SQL_SS_TIME2

### ISSUE THREAD

**Issue by lexicalunit** [nanodbc/nanodbc#18] opened 2017-10-13 23:18 UTC
_From @mloskot on November 21, 2016 10:16_

While using the ODBC Driver 11 for SQL Server, I noticed it is not possible to get data from `TIME` column.

TL:TR; nanodbc expects `SQL_TIME` while the SQL Server driver reports `TIME` as SQL Server-specific (SS) type `SQL_SS_TIME2 (-154)`.

## Problem
Currently, nanodbc handles `SQL_TIME` (ODBC 2.x) or `SQL_TYPE_TIME` (ODBC 3.x).

The SQL Server 2008 added [new date and time types ](https://msdn.microsoft.com/en-us/library/cc280460.aspx), namely `SQL_SS_TIME2`. In theory, uses of old `SQL_TIME` should work without modifications required:

> The new SQL Server time data type has fractional seconds accurate to 100 nanoseconds (...)
> Existing applications written to use times with no fractional seconds can use time(0) columns.
> The existing ODBC SQL_TYPE_TIME types and their corresponding structs should work correctly,
> unless the applications rely on the type returned in metadata.

AFAICT, it does not. I tried to create table with `time(0)` hoping to get it reported as  `SQL_TIME` or `SQL_TYPE_TIME`, but the driver still reports `SQL_SS_TIME2` which nanodbc falls back to bind it as `SQL_(W)CHAR` which in turn fails to translate to `nanodbc::time`.

Interestingly, [Data Type Support for ODBC Date and Time Improvements](https://msdn.microsoft.com/en-us/library/ms712408.aspx) does not even list  `SQL_TIME` or `SQL_TYPE_TIME` type as supported anymore. Mess squared!

BTW, since, the date and time data types that were added in SQL Server 2008, users of other drivers like 
SQL Server Native Client are likely affected too.

## Possible solution

Simplest, would be to handle all SQL Server-specific `SQL_SS_*` codes

Complete list is defined in
* `SQLNCLI.H` - part of the old SQL Server Native Client driver
* `msodbcsql.h` - part of the new [Microsoft ODBC Driver for SQL Server ](https://msdn.microsoft.com/en-us/library/jj730315.aspx)
* or here http://www.easysoft.com/developer/languages/c/examples/ListDataTypes.html

```
// Driver specific SQL data type defines.
// Microsoft has -150 thru -199 reserved for Microsoft SQL Server Native Client driver usage.
#define SQL_SS_VARIANT                      (-150)
#define SQL_SS_UDT                          (-151)
#define SQL_SS_XML                          (-152)
#define SQL_SS_TABLE                        (-153)
#define SQL_SS_TIME2                        (-154)
#define SQL_SS_TIMESTAMPOFFSET              (-155)
```

along with the corresponding ODBC C type constants:

```
// Extended C Types range 4000 and above. Range of -100 thru 200 is reserved by Driver Manager.
#define SQL_C_TYPES_EXTENDED                0x04000L
#define SQL_C_SS_TIME2                         (SQL_C_TYPES_EXTENDED+0)
#define SQL_C_SS_TIMESTAMPOFFSET               (SQL_C_TYPES_EXTENDED+1
```

and time-related structures: 
* `SQL_SS_TIME2_STRUCT`
* `SQL_SS_TIMESTAMPOFFSET_STRUCT`

Note, the structures (and their `sizeof`) are used in binding, similarly to their simpler counterparts:
* `SQL_TIME_STRUCT`
* `SQL_TIMESTAMP_STRUCT`:

In nanodbc, we may need to provide additional equivalent types, e.g.
* `nanodbc::time2`
* `nanodbc::timestamp_tz`

### Question

Can we be certain that no other drivers use the same codes like `-154` for their ODBC DBMS-specific data types?

I think we can't but there seem to be no better option than to take the risk, release nanodbc to the wild find out.

Any feedback is highly appreciated.

_Copied from original issue: lexicalunit/nanodbc#226_

**Comment by lexicalunit** [comment] 2017-10-13 23:18
_From @mloskot on November 21, 2016 10:17_

This general issue is related to more specific reported in #224

**Comment by lexicalunit** [comment] 2017-10-13 23:18
We could support these additional types but put the feature behind a flag like `NANODBC_ENABLE_SQL_SERVER_TIME_TYPES` so that, in the case that there are type code conflicts with other drivers, we can have a workaround.

**Comment by lexicalunit** [comment] 2017-10-13 23:18
_From @mloskot on November 21, 2016 16:16_

Following your later note in https://github.com/lexicalunit/nanodbc/pull/228#discussion_r88927314, let's try to implement those missing features without any additional flags, in master. If necessary, we can always decide and introduce conditional compilation for them later.

**Comment by lexicalunit** [comment] 2017-10-13 23:18
_From @mloskot on November 22, 2016 22:6_

We have it confirmed other drivers would fail to bind columns as `SQL_C_SS_*` types (see https://github.com/lexicalunit/nanodbc/issues/224#issuecomment-262378395 for pgsqlODBC story), 

It means, if we want to support types like `SQL_C_SS_TIMESTAMPOFFSET`, it needs to be based on run-time condition depending on driver, like so:

```
// auto_bind
case SQL_TIMESTAMP:
case SQL_TYPE_TIMESTAMP:
case SQL_SS_TIMESTAMPOFFSET:
     if (driver is SQL Server)
         col.ctype_ = SQL_C_SS_TIMESTAMPOFFSET;
     else
         col.ctype_ = SQL_C_TIMESTAMP;
...
```

Also, `sizeof(timestamp)` would not be suitable and separate structure like `timestamp_tz`  based on `SQL_SS_TIMESTAMPOFFSET_STRUCT` layout would be required.

Anyhow, not easy to handle those DBMS/driver-specifics without messing the core code a bit.

What you think?

**Comment by mkaes** [comment] 2021-04-21 13:07
Are there any plans to integrate the mentioned fix from r-dbi/odbc into nanodbc?
While it does not fix the timestamp type at least the strings can be read from the DB without adjustment.

**Comment by mloskot** [comment] 2021-04-21 13:12
> Are there any plans to integrate the mentioned fix from r-dbi/odbc into nanodbc?

PRs are always welcome

**Comment by mkaes** [comment] 2021-04-22 13:40
I removed my PR again because adding the patch will change API behaviour.
Currently a `datetimeoffset` can be queried as a `nanodbc::timestamp`.
With the patch this is no longer possible. I would argue that this is correct as the `nanodbc::timestamp` most probably has the wrong values. So it is useless.
I am using using c++20 date library. This means I can easily parse the string dates and get the timezone correctly.
For my use case the string handling is definitly better.

So I can add my pull request again and remove the unit test that gets the `datetimeoffset` as a `timestamp`, but is this kind of api change acceptable?

**Comment by mloskot** [comment] 2021-04-23 07:01
@lexicalunit ☝️ What you think?

**Comment by lexicalunit** [comment] 2021-04-23 19:26
For sure. If the `nanodbc::timestamp` type as currently is really useless, then it should be fixed. Anyone who wants the old API can easily use a previous release of the library.

**Comment by mloskot** [comment] 2021-04-23 19:56
@lexicalunit I agree. Since that is `auto_bind`, we can not support both to let users do either `result.get<std::string>("mytime")` or `result.get<nanodbc::timestamp>("mytime")`, no late binding there.

@mkaes Feel free to re-open your PR, but it will also have to adjust the tests.

**Comment by mkaes** [comment] 2021-04-26 15:49
I re-opened my PR but it fails.
I cannot tell what the problem of travis is and I cannot link the errors from appveyor to my pull request.

If I find some time I will try to figure out why appveyor fails but unfortunatly I don't have a VS 2017 at hand and it seems the issue is from the static code analysis.

**Comment by mloskot** [comment] 2021-04-28 20:16
@mkaes Please give me a few days to get our CI fixed. Thanks for the PR

**Comment by mloskot** [comment] 2021-12-23 22:22
@mkaes Can this one be also closed by https://github.com/nanodbc/nanodbc/pull/272 ?

**Comment by mkaes** [comment] 2022-01-19 14:57
@mloskot Sorry for the late reply I was on vacation. I am not sure if #272 covers all odbc date time types.
But I guess it should so this one should also be done with #272.

**Closed** 2022-01-19 17:31 UTC
Labels: category/feature
